In [1]:
import numpy as np,random as rd

In [ ]:
#1. what is the difference between list and array (min of 4 points )

#answer)a.list is a collection datatype which stores same or different type of data but array can only store same type of data
#       b.list has only single  dimensional  but array has n dimensional array upto 32
#       c.computation is slow  in list but  in array computation is very fast as compared to list
#       d.list occupies large amount of memory as dynamically allocated but in array more compact in memory size as we can mention the numpy datatype to be used
#       e.list can be appended and size can be extended but in array once array size is created we cannot increase the size

In [ ]:
#2 Write python code to create 3d array in different ways with 15 elements.(Min of 3 ways )
b=np.arange(1,16)
print("method one :")
print(b.reshape(3,1,5))
x=np.full((4,1,5),1)
print("method two :")
print(x)
y=np.zeros((5,1,4))
print("method three :")
print(y)

method one :
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]
method two :
[[[1 1 1 1 1]]

 [[1 1 1 1 1]]

 [[1 1 1 1 1]]

 [[1 1 1 1 1]]]
method three :
[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]


In [ ]:
#3 how will you prove that arrays are faster than lists,and whhy it is faster tell it in a point.
#
#list
import time
st=time.time()
l=[]
for y in range(1,10000000):
 l.append(y*2)
et=time.time()
print("time taken to print list :",et-st)
#array
st=time.time()
x=np.arange(1,10000000)*2
et=time.time()
print("time taken to print array :",et-st)
print("from above example we  have proved that array are faster then list")

time taken to print list : 3.0195298194885254
time taken to print array : 0.03105902671813965
from above example we  have proved that array are faster then list


In [ ]:
#4 Array Creation:
#a.Create a 4D NumPy array containing the first 12 positive integers as arr1,ofter creating check the dimension of the array and also dtype of the elements.
#b.Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1 and make every element as string.and ofter creating check what is the shape of the array.
arr1=np.arange(1,13).reshape(2,2,1,3)
print(arr1)
print("the dimension of the array is :",arr1.ndim)
print("the datatype of the array is :",arr1.dtype)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]
the dimension of the array is : 4
the datatype of the array is : int64


In [12]:
#b
a=np.random.random(((4,5))).reshape(2,2,5)
a=a.astype("str")#changing the datatype to string
print(a)
print("the shape of the array is :",a.shape)

[[['0.5977010392652589' '0.6826093829215023' '0.38326617014564757'
   '0.4780717431191577' '0.7850600034541854']
  ['0.8937315799426642' '0.7417767307787082' '0.8806871209114402'
   '0.16560344554929862' '0.23138826447965077']]

 [['0.8143718102539221' '0.20492453713936787' '0.44753968957002976'
   '0.917697584514315' '0.9752642655147367']
  ['0.7751180549516307' '0.5479581097375532' '0.12084414281502887'
   '0.2103077748256591' '0.4035320676940123']]]
the shape of the array is : (2, 2, 5)


In [14]:
 #5 create an array with all zeros without using np.zeros method.
ary=np.full((4,5),0,)
print("created an array with all zeros without using np.zeros method \n",ary)

created an array with all zeros without using np.zeros method 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
#6 create an array and perform all the arthamatic operations on it
ary=np.array([10,20,30,40,50])
print("addition of  array with 5 :",np.add(ary,5))
print("subtraction of the array with 5 :",np.subtract(ary,5))
print("mutlipication of the array with 5 :",np.multiply(ary,5))
print("division of the array with 10 :",np.divide(ary,10))
print("modulus of the array with 5 :",np.mod(ary,5))


addition of  array with 5 : [15 25 35 45 55]
subtraction of the array with 5 : [ 5 15 25 35 45]
mutlipication of the array with 5 : [ 50 100 150 200 250]
division of the array with 10 : [1. 2. 3. 4. 5.]
modulus of the array with 5 : [0 0 0 0 0]


In [21]:
#7 Create a 2x2 matrix A with elements from 1 to 4 and another matrix B with elements from 5 to 8.
#a. Add matrices A and B.
#b. Multiply matrices A and B element-wise.
#c. Find the dot product of matrices A and B.
A=np.arange(1,5).reshape(2,2)
B=np.arange(5,9).reshape(2,2)
print("matrice of A :\n",A)
print("matrice of B :\n",B)
print("addition of matrices A and B is :\n ",)
print(A+B)
print("multiplication of matrices A and B is :\n ",A*B)
array=np.dot(A,B)
print("dot product of matrices A and B is : \n",array)

matrice of A :
 [[1 2]
 [3 4]]
matrice of B :
 [[5 6]
 [7 8]]
addition of matrices A and B is :
 
[[ 6  8]
 [10 12]]
multiplication of matrices A and B is :
  [[ 5 12]
 [21 32]]
dot product of matrices A and B is : 
 [[19 22]
 [43 50]]


In [28]:
#8 Create a 3x3 matrix C with random integers.
#a. Find the sum of each row in matrix C.
#b. Find the sum of each column in matrix C.
#c. Find the product of all elements in matrix C.
c=np.random.randint(1,10,(3,3))
print("random integers between 1,10 :\n",c)
print("the sum of each row in matrix c :\n",np.sum(c,axis=1))
print("the sum of each column in matrix c :\n",np.sum(c,axis=0))
print("the product of all elements in matrix c :\n",np.prod(c))

random integers between 1,10 :
 [[6 6 5]
 [9 9 3]
 [2 8 2]]
the sum of each row in matrix c :
 [17 21 12]
the sum of each column in matrix c :
 [17 23 10]
the product of all elements in matrix c :
 1399680


In [46]:
#9 a. Create a boolean array based on whether elements in matrix C are greater than 0.
#  b. Use logical AND operation to find elements greater than 2 and less than 5 in matrix C.
m=c>0
print("the elements in matrix c are greater than 0 :\n",m)
x=np.logical_and(c>2,c<5)
print("the elements greater than 2 and less than 5 in matrix c :\n",x)

the elements in matrix c are greater than 0 :
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
the elements greater than 2 and less than 5 in matrix c :
 [[False False False]
 [False False  True]
 [False False False]]


In [45]:
#10 a. Access the element in the second row and third column of matrix C.
# b. Slice the first two columns of matrix C.
# c. Extract all elements greater than 3 from matrix C.
y=c[1,2]
print("accesing the element in the second row and third column of matrix c :\n",y)
z=c[ : , :2]
print("slicing the first two colums of matrix c :\n",z)
x=c[c>3]#using masking
print("the elements are greter than 3 from matrix c :\n",x)



accesing the element in the second row and third column of matrix c :
 3
slicing the first two colums of matrix c :
 [[6 6]
 [9 9]
 [2 8]]
the elements are greter than 3 from matrix c :
 [6 6 5 9 9 8]
